services:
  mysql:
    container_name: pop_mysql
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: 'root1234'
      MYSQL_DATABASE: 'pop'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user1234'
    ports:
      - '3306:3306'
    volumes:
      - mysql_volume:/var/lib/mysql

  redis:
    container_name: pop_redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/data

volumes:
  mysql_volume:
  redis_volume:
