spring:
  application:
    name: backend

  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_SECRET}
            client-name: kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS}
        secret-key: ${AWS_SECRET}
      s3:
        bucket: ${S3_BUCKET}
      region:
        static: ap-northeast-2

  jpa:
    properties:
      hibernate:
        dialect: com.hiddenartist.backend.global.db.CustomMySQLDialect

secret:
  jwt: ${JWT_SECRET}
  kakao-admin: ${KAKAO_ADMIN}

logging:
  config: classpath:log4j2/log4j2.yml

redirect-url:
  login-success: http://localhost/login-success
  logout: http://localhost/