name: POP Springboot Build Workflow

on:
  workflow_call:
    secrets:
      KAKAO_ID:
        required: true
      KAKAO_SECRET:
        required: true
      KAKAO_ADMIN:
        required: true
      JWT_SECRET:
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Git Clone Repository
        uses: actions/checkout@v4

      - name: Setup JDK temurin 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Redis
        uses: supercharge/redis-github-action@1.8.0

      - name: Grant execute permission to Gradlew
        run: chmod +x ./gradlew
        working-directory: ./backend

      - name: Build With Gradle Wrapper
        run: ./gradlew clean build --info
        working-directory: ./backend
        env:
          KAKAO_ID: ${{secrets.KAKAO_ID}}
          KAKAO_SECRET: ${{secrets.KAKAO_SECRET}}
          KAKAO_ADMIN: ${{secrets.KAKAO_ADMIN}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}