name: POP Springboot Build Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Git Clone Repository
        uses: actions/checkout@v4

      - name: Setup JDK temurin 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      #      - name: Setup Redis
      #        uses: supercharge/redis-github-action@1.8.0

      - name: Grant execute permission to Gradlew
        run: chmod +x ./gradlew
        working-directory: ./backend

      - name: Build With Gradle Wrapper
        run: ./gradlew clean build --info
        working-directory: ./backend