name: POP Backend Pull Request Workflow

on:
  pull_request:
    branches: ['main','develop']
    paths:
      - './backend/**'

jobs:
  backend-build:
    uses: ./.github/workflows/backend-build.yml
    secrets: inherit
    permissions:
      contents: read