name: POP Backend Pull Request Workflow

on:
  pull_request:
    branches: ['main','develop']
    paths:
      - './backend/**'

jobs:
  backend-build:
    uses: kihong1602/POP/.github/workflows/backend-build.yml@chore/back/github-actions-ci
    secrets: inherit
    permissions:
      contents: read