name: HiddenArtist Backend Pull Request Workflow

on:
  pull_request:
    branches: [ 'main','develop' ]
    paths:
      - 'backend/**'
      - '.github/**'

jobs:
  backend-build:
    uses: ./.github/workflows/backend-build.yml
    permissions:
      contents: read
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
      event: ${{ github.event_name }}