name: POP Backend Push Workflow

on:
  push:
    branches: ['feature/**','chore/**','fix/**','refactor/**']
    paths:
      - './backend/**'

jobs:
  backend-build:
    uses: kihong1602/POP/./github/workflows/backend-build.yml@chore/back/github-actions-ci
    secrets: inherit
    permissions:
      contents: read