name: HiddenArtist Backend Push Workflow

on:
  push:
    paths:
      - 'backend/**'
      - '.github/**'

jobs:
  backend-build:
    uses: ./.github/workflows/backend-build.yml
    permissions:
      contents: read
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
      event: ${{ github.event_name }}

  backend-deploy:
    needs: backend-build
    if: ${{ github.repository == 'Team-ToArt/HiddenArtist-Service' && github.ref_name == 'main' && github.event_name == 'push'}}
    uses: ./.github/workflows/backend-deploy.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit